apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-dp
  namespace: demo-ns
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      name: onlinebookstore-pod
      labels:
        app: bookstore
    spec:
      containers:
      - name: onlinebookstore-container
        image: shekardockerreg/multistage:2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-dp-svc
  namespace: demo-ns
spec:
  type: NodePort
  selector:
    app: bookstore
  ports:
  - port: 80
    targetPort: 8080
